/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as appLayoutRouteImport } from './pages/(app)/_layout'
import { Route as appinventoryLayoutRouteImport } from './pages/(app)/(inventory)/_layout'
import { Route as appActivityHistoryIndexRouteImport } from './pages/(app)/activity-history/index'
import { Route as appinventoryIndexRouteImport } from './pages/(app)/(inventory)/index'

const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appinventoryLayoutRoute = appinventoryLayoutRouteImport.update({
  id: '/(inventory)',
  getParentRoute: () => appLayoutRoute,
} as any)
const appActivityHistoryIndexRoute = appActivityHistoryIndexRouteImport.update({
  id: '/activity-history/',
  path: '/activity-history/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appinventoryIndexRoute = appinventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appinventoryLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appinventoryIndexRoute
  '/activity-history/': typeof appActivityHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appinventoryIndexRoute
  '/activity-history': typeof appActivityHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appLayoutRouteWithChildren
  '/(app)/(inventory)': typeof appinventoryLayoutRouteWithChildren
  '/(app)/(inventory)/': typeof appinventoryIndexRoute
  '/(app)/activity-history/': typeof appActivityHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity-history/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity-history'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/(inventory)'
    | '/(app)/(inventory)/'
    | '/(app)/activity-history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(inventory)': {
      id: '/(app)/(inventory)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appinventoryLayoutRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/activity-history/': {
      id: '/(app)/activity-history/'
      path: '/activity-history'
      fullPath: '/activity-history/'
      preLoaderRoute: typeof appActivityHistoryIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/(inventory)/': {
      id: '/(app)/(inventory)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appinventoryIndexRouteImport
      parentRoute: typeof appinventoryLayoutRoute
    }
  }
}

interface appinventoryLayoutRouteChildren {
  appinventoryIndexRoute: typeof appinventoryIndexRoute
}

const appinventoryLayoutRouteChildren: appinventoryLayoutRouteChildren = {
  appinventoryIndexRoute: appinventoryIndexRoute,
}

const appinventoryLayoutRouteWithChildren =
  appinventoryLayoutRoute._addFileChildren(appinventoryLayoutRouteChildren)

interface appLayoutRouteChildren {
  appinventoryLayoutRoute: typeof appinventoryLayoutRouteWithChildren
  appActivityHistoryIndexRoute: typeof appActivityHistoryIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appinventoryLayoutRoute: appinventoryLayoutRouteWithChildren,
  appActivityHistoryIndexRoute: appActivityHistoryIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
